python main_train.py \
--image_dir /data/serverC/Projects/R2Gen-Mamba/datasets/UAPD/JPEGImages \
--ann_path /data/serverC/Projects/R2Gen-Mamba/datasets/UAPD/annotations-split.json \
--dataset_name UAPD \
--max_seq_length 100 \
--threshold 3 \
--batch_size 16 \
--epochs 100 \
--save_dir results/UAPD \
--step_size 1 \
--gamma 0.8 \
--d_vf 2048 \
--seed 9223
